---
development:
  cloud_name: ebrahim-elgaml
  api_key: '389396188147695'
  api_secret: 2eRpnrFd0ooaU5RzCaFGKHWwrGk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ebrahim-elgaml
  api_key: '389396188147695'
  api_secret: 2eRpnrFd0ooaU5RzCaFGKHWwrGk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ebrahim-elgaml
  api_key: '389396188147695'
  api_secret: 2eRpnrFd0ooaU5RzCaFGKHWwrGk
  enhance_image_tag: true
  static_image_support: false
